### ISSUE TITLE
Backspace Key not deleting

### ISSUE THREAD

**Issue by yamunan-bitset** [troglobit/mg#13]
Hello, as I read in the `tutorial` file, it said ```To delete characters, use the backspace key.``` But when I did backspace, it showed ```a b c:```. I am not sure if this has a different meaning, but it would be useful to have a  backspace working rather than moving one letter forward and doing ^D.
Thanks

**Comment by troglobit** [comment]
Please tell me more about your operating system and the terminal your are using when you run into this problem. Also, how did you compile and run mg, or did you use a pre-built image? Anything to help reproduce your issue would be greatly appreciated!

I and many others have been using Mg successfully since years on standard Linux and BSD systems, as well as very limited embedded systems, not once have I heard of a problem with backspace. So you really need to reveal a bit more about your setup.

**Comment by yamunan-bitset** [comment]
I am running Arch Linux x86_64 on xterm. So I installed mg through ```sudo pacman -S mg```. I am using ```en_GB.UTF-8``` as my locale. I have tried other locales including ```en_US.UTF-8```, but the same problem occured.

**Comment by yamunan-bitset** [comment]
Seems like my terminal was sending ^H instead of ^?. So I added this line in my .Xresources

```
xterm.*backarrowKey: false
```

Now it seems to work

**Comment by troglobit** [comment]
This is not the upstream project of Mg for your package.
