### ISSUE TITLE
no visuals on cygwin until press any key

### ISSUE THREAD

**Issue by chrisbitmead** [troglobit/mg#19]
after building mg on cygwin and typing:
mg
nothing seemingly happens. But if I then press any key, the normal emacs screen appears.

**Comment by chrisbitmead** [comment]
I just realised this only happens in Windows terminal, not in the old style basic cygwin terminal. Probably not mg's fault, but might be a good place here for someone to tell us the solution.

**Comment by troglobit** [comment]
Interesting! I've only ever run cygwin in its own terminal, how would one go about reproducing this, i.e., how do I use Windows terminal with cygwin? (Don't even know where to download that...)

**Comment by troglobit** [comment]
OK, I've now managed to reproduce this.  Like you say, works in the default Cygwin terminal, but not in Windows Terminal.

This happens because of the limited support in the fallback `src/ansi.c`, which is used if a proper termcap/ncurses library is not found when running `./configure`.

To fix, install `ncurses-devel` in Cygwin setup.exe, re-run the configure script and rebuild.

**Comment by chrisbitmead** [comment]
Hi, sorry for the late response, and thankyou for figuring this out!

I don't know what the "fallback" is or where it came from, but give that the top platform is windows and the official terminal is now Windows terminal, it might be nice if the "fallback" supported that. Just a thought.

**Comment by troglobit** [comment]
Windows is hardly the top platform for Mg.  Windows is supported by installing the standard ncurses library, if that is missing a crude built-in fallback is used that works on standards compliant VT100/VT220 terminals.  

Sure, both the documentation and the fallback can be improved.  The fallback made to work around bugs in Windows terminal, but that is not really my priority since I don't use Windows at all.  If someone finds this a worthy enough exercise I'm sure they'll send a pull request to address the issue.
